---
# tasks file for python
      - name: Install all required dependencies
        dnf:
          name: '{{ item }}'
          state: present
        with_items:
          - python
          - python-setuptools
          - "@Development Tools"
          - python3-devel
          - python-pip